# Generated by Django 4.2.19 on 2025-05-22 07:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("SigninManager", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Event",
            new_name="SignEvent",
        ),
    ]
