# Generated by Django 4.2.19 on 2025-06-09 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SigninManager", "0002_rename_event_signevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancerecord",
            name="checkin_lat",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="checkin_lng",
        ),
        migrations.RemoveField(
            model_name="signevent",
            name="gps_lat",
        ),
        migrations.RemoveField(
            model_name="signevent",
            name="gps_lng",
        ),
        migrations.RemoveField(
            model_name="signevent",
            name="valid_radius",
        ),
    ]
