# Generated by Django 5.0.3 on 2025-05-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('expected_count', models.PositiveIntegerField()),
                ('actual_count', models.PositiveIntegerField()),
            ],
        ),
    ]
